name: "LSpec CI"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - name: Install Lean
        run: nix-shell
      - name: Log versions
        run: lean --version && lake --version
      - name: run LSpec binary
        run: lake exe lspec
